### PR TITLE
[JBPM-10120] Removed conflicting dependencies from kie-service-spring…

### PR DESCRIPTION
**Pull request by hbelmiro**
…-boot-archetype

I opened this PR to 7.x branch. I'm not sure this is correct.
I couldn't build the main branch since I couldn't find a 8.13.0-SNAPSHOT version of droolsjbpm-integration.
Please let me know if I need to fix anything.

**JIRA**: https://issues.redhat.com/browse/JBPM-10120

----

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by hbelmiro** [comment]
Jenkins run cdb

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
> I opened this PR to 7.x branch. I'm not sure this is correct. I couldn't build the main >branch since I couldn't find a 8.13.0-SNAPSHOT version of droolsjbpm-integration. Please let >me know if I need to fix anything.

Droolsjbpm-integration is not on 8.x stream only Drools -> Droolsjbpm-knowdledge ;)

So it is ok to target 7.x

**Comment by Ginxo** [comment]
Jenkins retest this

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
failed test is in kie-server [org.kie.server.client.LoadBalancerClientTest.testDefaultLoadBalancerNoServersAvailable](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.x/job/fdb/job/droolsjbpm-knowledge-7.x.fdb/10/testReport/org.kie.server.client/LoadBalancerClientTest/testDefaultLoadBalancerNoServersAvailable/)

**Comment by mareknovotny** [comment]
jenkins do cdb

**Comment by hbelmiro** [comment]
jenkins do cdb

**Comment by hbelmiro** [comment]
jenkins do cdb

**Comment by hbelmiro** [comment]
@mareknovotny, Compile Downstream Build is failing with random errors each time. I don't know what may be happening.
It runs locally without errors.

**Comment by mareknovotny** [comment]
ok, just try once FDB and merge if green or not related failures

jenkins run FDB

**Comment by hbelmiro** [comment]
FDB green @mareknovotny.
Can you merge, please? I don't have permission.

**Comment by mareknovotny** [comment]
could you please backport it to 7.67.x and 7.67.x-blue branches? thanks in advance @hbelmiro

**Pull request merged**
