### PR TITLE
RHDM-594 Remove drools-pmml dependency

### PR DESCRIPTION
**Pull request by lanceleverich**
Added more methods to enable adding base typed parameters to the PMMLRequestData

### CODE REVIEW

**Comment by mareknovotny** [comment]
Is this PR still relevant?

**Comment by mareknovotny** [comment]
ok to test

**Comment by mareknovotny** [comment]
@gitgabrio I think we can close this right?

**Comment by gitgabrio** [comment]
@mareknovotny 
Yes, fine to close. Thanks!

**Pull request closed without merging**
