### PR TITLE
JBPM-8078 - Change jbpm business service app configuration from prope…

### PR DESCRIPTION
**Pull request by tsurdilo**
…rty files to yaml

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski i know there is no need to do this but with this change we can give users benefits of yaml over property files and also support for utf-16 and utf-32

**Comment by mswiderski** [comment]
@tsurdilo I would not go completely to yaml ... properties is still easier to consume ... and less error prone :) Users can easily get that if they like ... though I wouldn't add this by default

**Comment by tsurdilo** [comment]
@mswiderski oh ok . i thought yaml is preferred as its much easier to read/consume but guess was wrong :) should i keep this pr around or just remove it ?

**Comment by tsurdilo** [comment]
Closing as we will use property files as default.

**Pull request closed without merging**
