### PR TITLE
[JBPM-9699] Register workitemhandler when Kafka extension is enabled

### PR DESCRIPTION
**Pull request by fjtirado**
Adding possibility of several default descriptors

**JIRA**: 

[link](https://issues.redhat.com/browse/JBPM-9699)

**referenced Pull Requests**: 
https://github.com/kiegroup/droolsjbpm-integration/pull/2455
https://github.com/kiegroup/jbpm/pull/1918

### CODE REVIEW

**Comment by fjtirado** [comment]
jenkins fdb

**Review by elguardian — APPROVED** [review]

**Review by gmunozfe — COMMENTED** [review]
Overall looks good, could you move the test classes from jbpm (as the code was moved as well)?

**Comment by fjtirado** [comment]
jenkins retest this

**Review by gmunozfe — CHANGES_REQUESTED** [review]
Missing DeploymentDescriptorManagerTest to be moved here

**Comment by fjtirado** [comment]
> Missing DeploymentDescriptorManagerTest to be moved here

That one depends on a jbmp parent class, I just copy the merged one. Also, it is good to leave the merged test on jbpm for redundancy (API on JBPM calls API on Knowledge, but if implementation is changed, it wont be detected on jbpm if I moved the test here, so it is better to copy and ensure that the logic of the merger worked without having to execute full downstream)

**Review by gmunozfe — APPROVED** [review]
ready to go, good job @fjtirado !

**Pull request merged**
