### PR TITLE
[Revert_PMML_Default] Reverting default to Legacy

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @mariofusco @jiripetrlik

Return LEGACY as PMML default

### CODE REVIEW

**Comment by gitgabrio** [comment]
Jenkins run fdb

**Comment by mariofusco** [comment]
jenkins execute fdb

**Comment by danielezonca** [comment]
jenkins execute fdb

**Comment by danielezonca** [comment]
jenkins execute fdb

**Comment by danielezonca** [comment]
Failed test are related to `jbpm` and are 404 so let's merge
```
org.kie.server.integrationtests.jbpm.BARuntimeDataServiceIntegrationTest.org.kie.server.integrationtests.jbpm.BARuntimeDataServiceIntegrationTest
org.kie.server.integrationtests.jbpm.ByPassUserTaskServiceIntegrationTest.org.kie.server.integrationtests.jbpm.ByPassUserTaskServiceIntegrationTest
org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest.org.kie.server.integrationtests.jbpm.ContainerFailureRecoveryIntegrationTest
org.kie.server.integrationtests.jbpm.ContainerUpdateIntegrationTest.org.kie.server.integrationtests.jbpm.ContainerUpdateIntegrationTest
org.kie.server.integrationtests.jbpm.DocumentServiceIntegrationTest.org.kie.server.integrationtests.jbpm.DocumentServiceIntegrationTest
org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest.org.kie.server.integrationtests.jbpm.ExceptionHandlingIntegrationTest
org.kie.server.integrationtests.jbpm.JobServiceIntegrationTest.org.kie.server.integrationtests.jbpm.JobServiceIntegrationTest
org.kie.server.integrationtests.jbpm.KieServerContainerListFilteringIntegrationTest.org.kie.server.integrationtests.jbpm.KieServerContainerListFilteringIntegrationTest
org.kie.server.integrationtests.jbpm.ProcessDefinitionIntegrationTest.org.kie.server.integrationtests.jbpm.ProcessDefinitionIntegrationTest
org.kie.server.integrationtests.jbpm.ProcessServiceIntegrationTest.org.kie.server.integrationtests.jbpm.ProcessServiceIntegrationTest
org.kie.server.integrationtests.jbpm.ProcessUserTaskServicesSecurityIntegrationTest.org.kie.server.integrationtests.jbpm.ProcessUserTaskServicesSecurityIntegrationTest
org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest.org.kie.server.integrationtests.jbpm.QueryDataServiceIntegrationTest
org.kie.server.integrationtests.jbpm.QueryInKjarIntegrationTest.org.kie.server.integrationtests.jbpm.QueryInKjarIntegrationTest
org.kie.server.integrationtests.jbpm.RollingUpdateUserTaskServiceIntegrationTest.org.kie.server.integrationtests.jbpm.RollingUpdateUserTaskServiceIntegrationTest
org.kie.server.integrationtests.jbpm.RuntimeDataServiceIntegrationTest.org.kie.server.integrationtests.jbpm.RuntimeDataServiceIntegrationTest
org.kie.server.integrationtests.jbpm.SLAComplianceIntegrationTest.org.kie.server.integrationtests.jbpm.SLAComplianceIntegrationTest
org.kie.server.integrationtests.jbpm.StartProcessServiceIntegrationTest.org.kie.server.integrationtests.jbpm.StartProcessServiceIntegrationTest
org.kie.server.integrationtests.jbpm.TimerIntegrationTest.org.kie.server.integrationtests.jbpm.TimerIntegrationTest
org.kie.server.integrationtests.jbpm.UserTaskServiceIntegrationTest.org.kie.server.integrationtests.jbpm.UserTaskServiceIntegrationTest
org.kie.server.integrationtests.jbpm.WebServiceIntegrationTest.org.kie.server.integrationtests.jbpm.WebServiceIntegrationTest
org.kie.server.integrationtests.jbpm.admin.ProcessInstanceAdminServiceIntegrationTest.org.kie.server.integrationtests.jbpm.admin.ProcessInstanceAdminServiceIntegrationTest
org.kie.server.integrationtests.jbpm.admin.ProcessInstanceMigrationIntegrationTest.org.kie.server.integrationtests.jbpm.admin.ProcessInstanceMigrationIntegrationTest
org.kie.server.integrationtests.jbpm.admin.UserTaskAdminServiceIntegrationTest.org.kie.server.integrationtests.jbpm.admin.UserTaskAdminServiceIntegrationTest
org.kie.server.integrationtests.jbpm.jms.JmsResponseHandlerIntegrationTest.org.kie.server.integrationtests.jbpm.jms.JmsResponseHandlerIntegrationTest
```

**Pull request merged**
