### PR TITLE
[DROOLS-4085] Added change set xsd to avoid fetching it from the inte…

### PR DESCRIPTION
**Pull request by lucamolteni**
…rnet

### CODE REVIEW

**Comment by kie-ci4** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by lucamolteni** [comment]
ok to test

**Comment by mareknovotny** [comment]
ok to test

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by lucamolteni** [comment]
Jenkins execute full downstream build

**Comment by lucamolteni** [comment]
Jenkins execute full downstream build

**Pull request merged**
