### PR TITLE
RHPAM-4779: New event when Process Instance related data changes

### PR DESCRIPTION
**Pull request by nmirasch**
**JIRA**: https://issues.redhat.com/browse/RHPAM-4779

Added a new event when Process Instance related data changes.

**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/646
* https://github.com/kiegroup/drools/pull/30
* https://github.com/kiegroup/jbpm/pull/2396
* https://github.com/kiegroup/droolsjbpm-integration/pull/3048

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by fjtirado — APPROVED** [review]

**Review by gmunozfe — COMMENTED** [review]
@nmirasch Compile downstream pipeline is failing here:
` Caused by: java.io.FileNotFoundException: /home/jenkins/workspace/KIE/7.x/compile/droolsjbpm-knowledge-7.x.compile/bc/kiegroup_droolsjbpm-integration/kie-server-parent/kie-server-services/kie-server-services-prometheus/target/classes (Is a directory)`

Probably it's unrelated but this makes  _Failed to execute goal org.revapi:revapi-maven-plugin:0.9.5:report (report) on project kie-server-rest-optaplanner_

**Comment by gmunozfe** [comment]
jenkins run cdb

**Comment by nmirasch** [comment]
jenkins run cdb

**Comment by mareknovotny** [comment]
here we need to run FDB @gmunozfe  /at the top of PR set ;) /

jenkins do fdb

**Comment by mareknovotny** [comment]
FDB fails here because there is taken wrong branch main for kie-jpmml-integration instead of 7.x branch.
We need to find out why.

**Comment by baldimir** [comment]
jenkins run cdb

**Pull request merged**
