### PR TITLE
AF-1799: Upgrade JDK 11 + GWT 2.9

### PR DESCRIPTION
**Pull request by caponetto**
**Upgrade JDK 11 + GWT 2.9**

Feel free to comment and/or raise any concerns.

This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039

Thanks guys for that!

**JIRA**:

[AF-1799](https://issues.redhat.com/browse/AF-1799)

**Parent Pull Request**:
- https://github.com/kiegroup/lienzo-core/pull/134

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Review by mariofusco — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do cdb

**Comment by mareknovotny** [comment]
CDB had a few Enforder duplicated classes errors
```
[2021-01-07T21:10:56.416Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-tasks-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[2021-01-07T21:10:56.416Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-tasks-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.416Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.416Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.416Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.416Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.416Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.416Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.416Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.416Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.416Z]     at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:243)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.416Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.416Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.416Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.416Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.416Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.416Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.416Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.416Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-sheets-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[2021-01-07T21:10:56.416Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-sheets-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.416Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:243)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-maps-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[2021-01-07T21:10:56.417Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-maps-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:243)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-drive-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[2021-01-07T21:10:56.417Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-drive-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:243)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-mail-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[2021-01-07T21:10:56.417Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-mail-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:243)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-calendar-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[2021-01-07T21:10:56.417Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (ban-duplicated-classes) on project google-calendar-workitem: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed.
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:243)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-01-07T21:10:56.417Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
[2021-01-07T21:10:56.417Z]     at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
[2021-01-07T21:10:56.417Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
[2021-01-07T21:10:56.417Z]     at java.lang.Thread.run (Thread.java:748)
[2021-01-07T21:10:56.417Z] [ERROR] 
[2021-01-07T21:10:56.417Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2021-01-07T21:10:56.417Z] [ERROR] 
[2021-01-07T21:10:56.417Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2021-01-07T21:10:56.417Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[2021-01-07T21:10:56.417Z] [ERROR] 
[2021-01-07T21:10:56.417Z] [ERROR] After correcting the problems, you can resume the build with the command
[2021-01-07T21:10:56.417Z] [ERROR]   mvn <args> -rf :google-tasks-workitem
[2021-01-07T21:10:56.715Z] + test 1 -eq 0
```
I retriggered it just to be sure. As https://github.com/kiegroup/jbpm-work-items/pull/162 is green this can be just a glitch in CI or in build

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins retest this

**Review by Srihari1192 — APPROVED** [review]

**Pull request merged**
