### PR TITLE
[RHPAM-4557] removed planner from archetype generation

### PR DESCRIPTION
**Pull request by lampajr**
**Thank you for submitting this pull request**

Removed _planner_  `appType` from archetype generation as there is no more OptaPlanner on `7.67.x-blue` branch.
I also updated the README to remove planner references.

**JIRA**: 

- https://issues.redhat.com/browse/RHPAM-4557

**referenced Pull Requests**: 

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
/
jenkins do fdb

**Comment by lampajr** [comment]
`Linux - Compile Downstream Build` is failing for this:
```
[2023-05-02T08:44:22.775Z] [ERROR] Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:6.1.2.Final:package (default) on project business-monitoring-webapp: Packaging wildfly failed: InvocationTargetException: Failed to get the list of the operation properties: "WFLYCTL0030: No resource definition is registered for address [
[2023-05-02T08:44:22.775Z] [ERROR]     ("subsystem" => "elytron"),
[2023-05-02T08:44:22.775Z] [ERROR]     ("filesystem-realm" => "KieRealm")
[2023-05-02T08:44:22.775Z] [ERROR] ]"
[2023-05-02T08:44:22.775Z] [ERROR] -> [Help 1]
[2023-05-02T08:44:22.775Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.plugins:wildfly-jar-maven-plugin:6.1.2.Final:package (default) on project business-monitoring-webapp: Packaging wildfly failed
```

**Comment by lampajr** [comment]
Jenkins run cdb

**Comment by mareknovotny** [comment]
cdb failure is known concurrent issue, not reproducible most of the times locally :(

**Review by rsynek — COMMENTED** [review]
I noticed there are more places that still mention OptaPlanner in the kie-archetypes directory:
https://github.com/kiegroup/droolsjbpm-knowledge/blob/7.67.x-blue/pom.xml#L18
https://github.com/kiegroup/droolsjbpm-knowledge/blob/7.67.x-blue/kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/static/index.html#L61

**Comment by lampajr** [comment]
> I noticed there are more places that still mention OptaPlanner in the kie-archetypes directory: https://github.com/kiegroup/droolsjbpm-knowledge/blob/7.67.x-blue/pom.xml#L18 https://github.com/kiegroup/droolsjbpm-knowledge/blob/7.67.x-blue/kie-archetypes/kie-service-spring-boot-archetype/src/main/resources/archetype-resources/src/main/resources/static/index.html#L61

I think all 7.67.x-blue branches are still mentioning OP somewhere, e.g., https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/7.67.x-blue/pom.xml#L27 - so for this PR I would just remove what is really breaking stuff, wdyt @mareknovotny @rsynek ? Otherwise not a big deal to remove them.

**Comment by rsynek** [comment]
@lampajr no preference here; just saying these are some mentions of optaplanner there.

**Review by rsynek — APPROVED** [review]

**Pull request merged**
