### PR TITLE
RHDM-766 /  DROOLS-3404

### PR DESCRIPTION
**Pull request by lanceleverich**
This PR combines the removal of all 'declare' statements from rules generated by PMML, and the addition of support for running containers that include PMML within kie-server, by using the ApplyPmmlModelCommand.

### CODE REVIEW

**Comment by jiripetrlik** [comment]
Can you be more specific in commit messages and description.
1. "Merge branch 'RHDM-766' into combined" - what does "combined" mean? Is it some branch or something?
2. "Removing all 'declare' statements, including those that..." - it seems that in this commit you are adding new classes to kie api. How is it related to removing of declare statements? Please change the commit message.

**Comment by lanceleverich** [comment]
Jenkins retest this

**Comment by jiripetrlik** [comment]
Looks good to me.

**Comment by etirelli** [comment]
jenkins retest this

**Pull request merged**
