### PR TITLE
JBPM-8166: case modeler - register the assets into the workbench and process engine

### PR DESCRIPTION
**Pull request by xiezhang7**
Assembly:
https://github.com/kiegroup/drools/pull/2257
https://github.com/kiegroup/droolsjbpm-knowledge/pull/370
https://github.com/kiegroup/jbpm/pull/1440

### CODE REVIEW

**Comment by xiezhang7** [comment]
Hi @romartin @LuboTerifaj , this pull request is for [JBPM-8166](https://issues.jboss.org/browse/JBPM-8166). Thanks.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
ping @LuboTerifaj  plz - urgent

**Comment by LuboTerifaj** [comment]
I cannot test it properly because there is an issue with kie-server:
`[org.kie.server.services.impl.controller.DefaultRestControllerImpl] (KieServer-ControllerConnect) Exception encountered while syncing with controller at http://localhost:8080/business-central/rest/controller/server/test-kie-server error Error while sending PUT request to http://localhost:8080/business-central/rest/controller/server/test-kie-server response code 405`.
Do you know, where could be a problem?

**Comment by romartin** [comment]
Hey @LuboTerifaj 
TBH I dont' know exactly what the issue could be now.. but an error code 405 indicates that the resource is not allowed. May be are you pointing to a wrong URL? It looks like the endpoint targets a resource which could not exist...
@wmedvede  any ideas on this? You've run the kie-seever with no issues recently isn't it?
Thanks!

**Comment by LuboTerifaj** [comment]
It seems that issue is present also on master. https://github.com/kiegroup/kie-wb-common/pull/2467 should fix it, so I need to wait until it will be merged.

**Comment by wmedvede** [comment]
> Hey @LuboTerifaj
> TBH I dont' know exactly what the issue could be now.. but an error code 405 indicates that the resource is not allowed. May be are you pointing to a wrong URL? It looks like the endpoint targets a resource which could not exist...
> @wmedvede any ideas on this? You've run the kie-seever with no issues recently isn't it?
> Thanks!

yes, but my local kie-server probably didn't have this "new" issue. Even so, I could see that artifacts for https://github.com/kiegroup/kie-wb-common/pull/2467 were generated, so I'll chase people in the PR if merge/test can be prioritized.

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@xiezhang7 @LuboTerifaj @wmedvede please this is an **URGENT** task to complete - please let's try to move this forward all together during today! Thanks!

**Comment by wmedvede** [comment]
Hi @pefernan @mswiderski @LuboTerifaj 

I'm trying to test this PR and for this I need both business-central and kie-server running.
Both artifacts are generated well, this is fine.

1) I install both business-central and kie-server in same WF14 I'm regulary using, same enviroment, etc, all is fine. Connection between them is fine.

2) I create a project and try to deploy. When I do this in business-cental I get this error:
"Deployment was skipped, couldn't find any server running in "regular" mode."

3) I stop all, and start all again passing this property
-Dorg.kie.server.mode=regular

4) when I start the second time I still get the error message:
"Deployment was skipped, couldn't find any server running in "regular" mode."

5) I start a third time and set a break point in kie-server and the property is apparently being loaded well, and regular mode is started.

6) but I always get the same error when trying to deploy from business-central

All the configurations in my environment are the same as before, the only new param added was 
org.kie.server.mode

I am missing any other configuration? or there's something that is not going well?

Thanks!

**Comment by pefernan** [comment]
@wmedvede looks like your business central hasn't detected the mode change on your kie-server (first started as dev mode and later you changed it to regular). Try start again changing the identifier of your kie-server.

**Comment by wmedvede** [comment]
@romartin @xiezhang7 @LuboTerifaj 
OK, I've talked with @pefernan  and this is what's going on. The first time kie-server was started the DEVELOPMENT mode was set (this is the by default) and it looks like business-central is "cashing" this state in the VFS. So all the next times I started the business-central the even when the server was in REGULAR mode, business-central has DEVELOPMENT mode.
That explains the behaviour above.

Going back to the test:
I started with a fresh new installation, and kie-server started with  -Dorg.kie.server.mode=regular

This time this are my findings:

Test1:
1) I create a regular project with a HelloWorld.bpmn-cm file
2) I deploy the project with no problems. I can see that the deployment unit was generated etc.
3) I go to the "Process Instances" perspective (ideally for starting the case) but I can't see the HelloWorld case listed in this screen.

Test2:
1) I create a case project with a HelloWorld.bpmn-cm file and a regular NormalProcess
2) I deploy the process with no problems. I can see the deployment unit was generated, etc.
3) I go to the "Process Instances" perspective but I can't see the HelloWorld case.
I can only see "NormapProcess".bpmn

So it looks like the "Process Instances" perspective is not displaying/integrating case files. See screenshot below.

I don't know if this is a bug or not since I don't know that the level of integration expectations are here.
i.e., Is it expected that users will be able to start the case management preview files from this perspective? or is it to early?
I hand this over to you guys @romartin @xiezhang7 @LuboTerifaj 

Thanks

screenshot from 2019-02-14 11-08-24

**Comment by xiezhang7** [comment]
> Hello @xiezhang7 , @romartin
> 
> I have found same issue as @wmedvede mentioned in comment above:
> 
> * After deploying project containing any valid bpmn-cm file, there is no process/case definition in Manage perspective.
> 
> The only way how to create case instance is to download it, change the file extension to bpmn and import it back.
> 
> Thank you!

Hi @LuboTerifaj ,

This issue is supposed to be fixed with the change in this [PR](https://github.com/kiegroup/jbpm/pull/1440). 

However, as @ibek pointed out in [JBPM-8166](https://issues.jboss.org/browse/JBPM-8166?focusedCommentId=13695649&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13695649), case should be handled in a custom build case management app, not in this perspective. Currently, we should try to start the case using REST API. I am not sure if there is anything else to verify after that.

I am still trying to deploy kie-server locally. But I don't know which REST API I should use to start the case.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by ibek** [comment]
You can find the REST API details in here: http://jbpm.org/api-docs/kie-server/paths.html#_startcase

@MarianMacik can help you with executing all the steps in the case if needed

**Pull request merged**
