### PR TITLE
custom banner for jbpm business apps and jbpm favicon

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
adds a custom banner when starting up the app that looks like this

screen shot 2018-10-15 at 10 10 08 pm

**Comment by cristianonicolai** [comment]
that looks cool! :)

**Comment by mswiderski** [comment]
@tsurdilo that is nice... just one comment maybe remove the "Welcome to your" so we stay jBPM Business Application, wdyt?

**Comment by tsurdilo** [comment]
@mswiderski sure, updated.

**Pull request merged**
