### PR TITLE
[DROOLS-1629] Allow backward compatibility without breaking interface

### PR DESCRIPTION
**Pull request by ngs-mtech**
As a result of https://github.com/kiegroup/drools/pull/1354, a new approach to solve the issue as suggested by mswiderski

### CODE REVIEW

**Comment by mswiderski** [comment]
ok to test

**Comment by mswiderski** [comment]
@ngs-mtech could you please apply the formatting as described here https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/README.md as you seem to have it different and makes a lot of changes while there are few lines added

**Comment by ngs-mtech** [comment]
I have fixed the issues reported by checkstyle.

**Comment by ngs-mtech** [comment]
Hi Maciej, thank you for your tips, here you have.

**Comment by ngs-mtech** [comment]
Hi Maciej, 
This pull request should be merged before the other one,
I don't know who have to do the merge and how it is done, this is new to me.

Regards.

**Pull request merged**
