### PR TITLE
[DO NOT MERGE] RHPAM-2120 Change the default strategy from Singleton to PerProcessInstance

### PR DESCRIPTION
**Pull request by bxf12315**
@cristianonicolai @nmirasch 
Please review it.

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by bxf12315** [comment]
> Looks good. @bxf12315 please have a look in JIRA, where I added a new comment. We should also change the KModuleDeploymentUnit class in the jbpm repo.

Issue https://issues.jboss.org/browse/RHPAM-2120

**Comment by bxf12315** [comment]
@cristianonicolai I think the PR related too many unit test(110), so the change maybe is not good. [PR](https://github.com/kiegroup/jbpm-wb/pull/1363) This PR has a relatively small range of influence.

**Comment by MarianMacik** [comment]
Many of these failures, if not all, are from jbpm repository. A lot of later fails may be just a consequence of previous tests.

**Comment by nmirasch** [comment]
@bxf12315 Correct me if I wrong but I think this default value should to be changed here too: https://github.com/kiegroup/droolsjbpm-integration/blob/1715d6cc0d52a2242d33ebc2904b1a41e00a4748/kie-server-parent/kie-server-controller-plugin/src/main/java/org/kie/server/controller/builder/ContainerBuilder.java#L69

**Comment by bxf12315** [comment]
> Many of these failures, if not all, are from jbpm repository. A lot of later fails may be just a consequence of previous tests.

ok, I will try to change KModuleDeploymentUnit and test it.

**Comment by bxf12315** [comment]
> @bxf12315 Correct me if I wrong but I think this default value should to be changed here too: [kiegroup/droolsjbpm-integration:kie-server-parent/kie-server-controller-plugin/src/main/java/org/kie/server/controller/builder/ContainerBuilder.java@`1715d6c`#L69](https://github.com/kiegroup/droolsjbpm-integration/blob/1715d6cc0d52a2242d33ebc2904b1a41e00a4748/kie-server-parent/kie-server-controller-plugin/src/main/java/org/kie/server/controller/builder/ContainerBuilder.java#L69)

I think you are right, but if I change it, how to verify it ?

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by bxf12315** [comment]
@jstastny-cz The PR related many unit-test failed(more than 150), It should not be merged.
You can see PR in here.https://github.com/kiegroup/jbpm/pull/1500

**Comment by jstastny-cz** [comment]
@bxf12315 you might want to close this one then. Or do you plan to work on it?

**Comment by bxf12315** [comment]
> @bxf12315 you might want to close this one then. Or do you plan to work on it?

I will work on it.

**Comment by jstastny-cz** [comment]
@bxf12315 then please add a label stating that it work in progress ... it might be sth like WIP or DO NOT MERGE. Thanks

**Comment by bxf12315** [comment]
> @bxf12315 then please add a label stating that it work in progress ... it might be sth like WIP or DO NOT MERGE. Thanks

ok

**Comment by bxf12315** [comment]
won't fix.

**Pull request closed without merging**
