### PR TITLE
JBPM-8607 Springboot kie-server sync with business-central controller…

### PR DESCRIPTION
**Pull request by sudhishmk**
… failing in DEV mode

### CODE REVIEW

**Comment by kie-ci10** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by sudhishmk** [comment]
Updated kieserver.controllers endpoint for application-dev.properties file.

**Comment by sudhishmk** [comment]
Can one of the admins verify this PR?

**Comment by mareknovotny** [comment]
ok to test

**Comment by mswiderski** [comment]
@sudhishmk thanks a lot for finding this and fixing

**Pull request merged**
