### PR TITLE
DROOLS-6458 Allow KieHelper to build model-based DRL from configuration

### PR DESCRIPTION
**Pull request by triceo**
**JIRA**: _(please edit the JIRA link if it exists)_ 

[DROOLS-6458](https://issues.redhat.com/browse/DROOLS-6458)

### CODE REVIEW

**Comment by mariofusco** [comment]
jenkins execute fdb

**Review by mariofusco — APPROVED** [review]

**Comment by triceo** [comment]
jenkins execute fdb

**Comment by triceo** [comment]
marek says jenkins execute fdb

**Comment by triceo** [comment]
jenkins execute fdb and please do not get stuck this time.

**Comment by triceo** [comment]
jenkins execute fdb, pretty pretty please.

**Comment by triceo** [comment]
wheels on the bus go round and round, round and round, round and round.
Jenkins execute fdb.

**Comment by rsynek** [comment]
jenkins execute fdb

**Comment by mbiarnes** [comment]
jenkins execute fdb

**Pull request merged**
