### PR TITLE
[DROOLS-4085] Added change set xsd to avoid fetching it from the internet

### PR DESCRIPTION
**Pull request by lucamolteni**
.

### CODE REVIEW

**Comment by mareknovotny** [comment]
ok to test

**Comment by mareknovotny** [comment]
Jenkins test this, please

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins execute full downstream build

**Comment by mareknovotny** [comment]
Jenkins retest this, please

**Comment by mareknovotny** [comment]
jenkins execute full downstream build

**Comment by lucamolteni** [comment]
jenkins execute full downstream build

**Comment by lucamolteni** [comment]
jenkins execute full downstream build

**Comment by lucamolteni** [comment]
jenkins execute full downstream build

**Comment by lucamolteni** [comment]
jenkins execute full downstream build

**Comment by lucamolteni** [comment]
jenkins execute full downstream build

**Comment by lucamolteni** [comment]
Jenkins retest this, please

**Comment by lucamolteni** [comment]
Jenkins retest this, please

**Pull request merged**
